language: go
go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master
notifications:
  email:
    recipients:
      - 1151510533@qq.com
    on_success: always

brfore_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci -v
  - go build
env:
  - GO111MODULE=on
branches:
  only:
    - master